# 1. Tên dự án (Giữ nguyên cái cũ của bạn)
spring.application.name=optistock-backend

# 2. Cấu hình kết nối MongoDB (QUAN TRỌNG NHẤT)
# Server sẽ tìm MongoDB ở máy bạn (localhost) cổng 27017
# Tên Database là 'optistock_db' (nếu chưa có nó tự tạo)
spring.data.mongodb.uri=mongodb://localhost:27017/optistock_db

# 3. Cổng chạy Server (Để khớp với Frontend gọi vào)
server.port=8080

# 4. Làm đẹp dữ liệu JSON trả về (Để bạn dễ đọc khi test)
spring.jackson.serialization.indent_output=true